version: '3.8'

x-aws-loadbalancer: ${ALB_ARN}

services:

    todo:
        image: robogeek/todo-app:first-dockerize-redis
        # container_name: todo-app
        ports:
          - "80:80"
        deploy:
            replicas: 1
        secrets:
            - sequelize_connect
        environment:
            - SEQUELIZE_CONNECT=/run/secrets/sequelize_connect
            - REDIS_ENDPOINT=redis.todo-docker-ecs.local
            # - NODE_DEBUG=redis
            # Enable this for debugging output ,socket.io:*
            - DEBUG=todos:*,ioredis:*,socket.io:*,engine
 
    redis:
        image: redis

secrets:
  sequelize_connect:
    external: true
    name: ${SEQUELIZE_CONNECT_ARN}
