version: '3.8'

x-aws-loadbalancer: ${ALB_ARN}

services:
  
    phpmyadmin:
        image: phpmyadmin
        # restart: always
        ports:
          - 80:80
        environment:
          - PMA_ARBITRARY=1
