version: '3.8'

services:
  
  phpmyadmin:
    image: phpmyadmin
    # restart: always
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1

# Assign domain name db.ROOT-DOMAIN
# Declare a security group and show using an external network
# The security group should specify a CIDR for home network
# Can demonstrate overriding Terraform variable defaults this way
