version: '3.8'
services:
  wordpress:
    image: wordpress:latest
    # deploy:
    #   replicas: 5
    ports:
      - 80:80
    # restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wpfs:/var/www/html

volumes:
  wpfs:
    external: true
    name: ${WP_EFS_ID}
